//! Shared message and provider abstractions for LLM backends.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;

use crate::principal::Principal;

/// Metadata returned by the provider for a single completion.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TurnMeta {
    /// Model that produced this turn.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Tokens consumed by input.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<u64>,
    /// Tokens produced as output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<u64>,
    /// Tokens used for reasoning (not injectable).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u64>,
    /// Reasoning trace text (saved but never re-injected).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_trace: Option<String>,
}

pub mod history_groups;
pub mod openai;

/// Role of a chat message in the message history.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ChatRole {
    System,
    User,
    Assistant,
    Tool,
}

/// Structured tool request from an assistant response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Identifier generated by the model for a tool invocation.
    pub id: String,
    /// Name of the function/tool to execute.
    pub name: String,
    /// Raw JSON argument string sent by the model.
    pub arguments: String,
}

impl ToolCall {
    /// Try to extract a `"command"` string from the JSON arguments.
    pub fn parse_command(arguments: &str) -> Option<String> {
        serde_json::from_str::<serde_json::Value>(arguments)
            .ok()?
            .get("command")?
            .as_str()
            .map(String::from)
    }
}

/// Structured result attached by tool execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    /// Identifier of the tool call this output belongs to.
    pub tool_call_id: String,
    /// Name of the tool that produced the output.
    pub name: String,
    /// Raw tool output as a string.
    pub content: String,
}

/// Message payload used in LLM request and response histories.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum MessageContent {
    /// Plain text message content.
    Text { text: String },
    /// Assistant requested tool execution.
    ToolCall {
        #[serde(flatten)]
        call: ToolCall,
    },
    /// Tool execution result.
    ToolResult {
        #[serde(flatten)]
        result: ToolResult,
    },
}

impl MessageContent {
    pub fn text(value: impl Into<String>) -> Self {
        Self::Text { text: value.into() }
    }

    pub fn tool_result(
        tool_call_id: impl Into<String>,
        name: impl Into<String>,
        content: impl Into<String>,
    ) -> Self {
        Self::ToolResult {
            result: ToolResult {
                tool_call_id: tool_call_id.into(),
                name: name.into(),
                content: content.into(),
            },
        }
    }
}

/// A chat message with a role and ordered list of content items.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Message sender role.
    pub role: ChatRole,
    /// Trust level of the message source.
    #[serde(default)]
    pub principal: Principal,
    /// Ordered chunks of message content.
    pub content: Vec<MessageContent>,
}

impl ChatMessage {
    pub fn with_role(role: ChatRole) -> Self {
        Self::with_role_with_principal(role, None)
    }

    pub fn with_role_with_principal(role: ChatRole, principal: Option<Principal>) -> Self {
        Self {
            role,
            principal: principal.unwrap_or_default(),
            content: Vec::new(),
        }
    }

    pub fn system(content: impl Into<String>) -> Self {
        Self::system_with_principal(content, None)
    }

    pub fn system_with_principal(content: impl Into<String>, principal: Option<Principal>) -> Self {
        Self {
            role: ChatRole::System,
            principal: principal.unwrap_or_default(),
            content: vec![MessageContent::text(content)],
        }
    }

    pub fn user(content: impl Into<String>) -> Self {
        Self::user_with_principal(content, None)
    }

    pub fn user_with_principal(content: impl Into<String>, principal: Option<Principal>) -> Self {
        Self {
            role: ChatRole::User,
            principal: principal.unwrap_or_default(),
            content: vec![MessageContent::text(content)],
        }
    }

    pub fn tool_result(
        tool_call_id: impl Into<String>,
        name: impl Into<String>,
        content: impl Into<String>,
    ) -> Self {
        Self::tool_result_with_principal(tool_call_id, name, content, None)
    }

    pub fn tool_result_with_principal(
        tool_call_id: impl Into<String>,
        name: impl Into<String>,
        content: impl Into<String>,
        principal: Option<Principal>,
    ) -> Self {
        Self {
            role: ChatRole::Tool,
            principal: principal.unwrap_or_default(),
            content: vec![MessageContent::tool_result(tool_call_id, name, content)],
        }
    }
}

/// Tool definition passed into provider calls.
#[derive(Debug, Clone)]
pub struct FunctionTool {
    /// Tool name used by model to choose execution.
    pub name: String,
    /// Human readable description.
    pub description: String,
    /// JSON schema describing tool input fields.
    pub parameters: Value,
}

/// Result of one streamed completion call.
#[derive(Debug, Clone)]
pub struct StreamedTurn {
    /// Assistant message for the current turn.
    pub assistant_message: ChatMessage,
    /// Parsed tool calls accumulated from the stream.
    pub tool_calls: Vec<ToolCall>,
    /// Optional turn-level metadata from provider completion usage.
    pub meta: Option<TurnMeta>,
    /// Why the stream ended.
    pub stop_reason: StopReason,
}

/// Normalized stop reason used by the agent loop.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StopReason {
    /// Model returned final text.
    Stop,
    /// Model requested one or more tool calls.
    ToolCalls,
}

/// Boxed future used by `LlmProvider` methods.
pub type BoxFutureLlm<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Abstraction over an LLM that can stream completion output.
pub trait LlmProvider {
    /// Build and send a completion request, invoking `on_token` on each token chunk.
    fn stream_completion<'a>(
        &'a self,
        messages: &'a [ChatMessage],
        tools: &'a [FunctionTool],
        on_token: &'a mut (dyn FnMut(String) + Send),
    ) -> BoxFutureLlm<'a, Result<StreamedTurn>>;
}
